#server.port: ${GATEWAY_SERVICE_PORT:8762}

eureka:
  client:
    registryFetchIntervalSeconds: 10
    serviceUrl.defaultZone: ${EUREKA_DEFAULT_ZONE_URL}
    healthcheck.enabled: true
    fetchRegistry: true
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /health
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    metadata-map:
      management:
        port: ${server.port}
        context-path: /


#management:
#  endpoints:
#    web:
#      base-path: /
#      exposure.include: "*"
#  endpoint:
#    health:
#      show-details: ALWAYS

spring:
    gateway:
      discovery.locator.enabled: true
      discovery.locator.lowerCaseServiceId: true
      routes:
        - id: regulations_route
          uri: lb://regulations
          predicates:
            - Path=/regulations/**
          filters:
            - PrefixPath=/regulations
        #          - RewritePath=/regulations/(?<segment>.*), /regulations/$\{segment}
        - id: document_types_route
          uri: lb://document-types
          predicates:
            - Path=/document-types/**
        #        filters:
        #          - PrefixPath=/document-types
        - id: documents_route
          uri: lb://document-types
          predicates:
            - Path=/documents/**
        #        filters:
        #          - PrefixPath=/documents
        - id: applications_route
          uri: lb://applications
          predicates:
            - Path=/applications/**
        #        filters:
        #          - PrefixPath=/applications
        - id: questionaries_route
          uri: lb://applications
          predicates:
            - Path=/questionaries/**
        #        filters:
        #          - PrefixPath=/questionaries
        - id: applicants_route
          uri: lb://applications/applicants
          predicates:
            - Path=/applicants/**
#        filters:
#          - PrefixPath=/applicants

turbine:
  instanceUrlSuffix: /hystrix.stream
  aggregator:
    clusterConfig: doctypes,regulations,applications
  appConfig: DOCUMENT-TYPES,REGULATIONS,APPLICATIONS

spring.boot.admin:
  client:
    url: ${ADMIN_URL}
    period: 10000
    instance:
      prefer-ip: true
      name: ${spring.application.name}:${spring.application.instance_id:${random.value}}
