eureka:
  client:
    registryFetchIntervalSeconds: 10
    serviceUrl.defaultZone: ${EUREKA_DEFAULT_ZONE_URL}
    healthcheck.enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /health
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    metadata-map:
      management:
        port: ${management.server.port}
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        context-path: /